site_name: My Docs

theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate

nav:
  - index.md
  - quickstart.md
  - Guides:
    - how-to.md
    - tutorials.md
    - explanation.md
  - examples.md
  - api.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js